- name: istio-default
  enricher:
    includes:
    - fmp-name
    - fmp-controller
    - fmp-service
    - fmp-image
    - fmp-portname
    - fmp-ianaservice
    - fmp-project
    - fmp-dependency
    - fmp-pod-annotations
    - fmp-git
    # TODO: Documents and verify enrichers below
    - fmp-debug
    - fmp-merge
    - fmp-remove-build-annotations
    - fmp-volume-permission
    # -----------------------------------------
    - f8-cd
    - f8-cd-doc-link
    - f8-cd-grafana-link
    - f8-icon
    # TODO: Document and verify enrichers below
    - f8-expose
    # Istio sidecar injection
    - fmp-istio-enricher
    # Health checks
    - spring-boot-health-check
    - wildfly-swarm-health-check
    - karaf-health-check
    - vertx-health-check
    - docker-health-check
    - f8-prometheus
    - f8-maven-scm
    - f8-maven-issue-mgmt
    # Dependencies shouldn't be enriched anymore, therefor it's last in the list
    - fmp-dependency
    - f8-watch
    - fmp-revision-history
    - fmp-docker-registry-secret
    excludes:
    - fmp-openshift-route
    config:
      fmp-istio-enricher:
        istioVersion: "0.4.0"
        enableCoreDump: "false"

  generator:
    includes:
    - spring-boot
    - wildfly-swarm
    - karaf
    - vertx
    - java-exec
    - webapp
  watcher:
    includes:
    - spring-boot
    - docker-image
